import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {handle} from '../src/worker.mjs';
import {matchListings} from '../src/matching.mjs';
import {database} from './helpers.mjs';
const month=()=>{const d=new Date();d.setUTCMonth(d.getUTCMonth()+2,1);return d.toISOString().slice(0,7);};
const profile=(who)=>({displayName:who,country:who==='bob'?'Taiwan':'India',preferredCurrency:who==='bob'?'TWD':'INR',destination:who==='bob'?'India':'Taiwan',travelMonth:month()});
const offer=(reverse=false)=>({have:reverse?'TWD':'INR',need:reverse?'INR':'TWD',amount:reverse?'3800':'10000',origin:reverse?'Taiwan':'India',destination:reverse?'India':'Taiwan',travelMonth:month(),note:'Fictional travel plan'});
function setup(){const DB=database(),env={DB,ADMIN_EMAIL:'owner@example.test'};const call=async(path,person='alice',data,headers={})=>{const r=await handle(new Request('https://travelswap.test/api/'+path,{method:data===undefined?'GET':'POST',headers:{...(person?{'oai-authenticated-user-id':person,'oai-authenticated-user-email':person+'@example.test'}:{}),...(data===undefined?{}:{origin:'https://travelswap.test','Content-Type':'application/json','X-TravelSwap-Request':'1'}),...headers},body:data===undefined?undefined:JSON.stringify(data)}),env);return {status:r.status,data:await r.json(),headers:r.headers};};return {DB,env,call};}
async function accounts(call){for(const p of ['alice','bob','eve','owner'])assert.equal((await call('profile',p,profile(p))).status,200);}
async function pair(call){await accounts(call);const a=await call('listings','alice',offer()),b=await call('listings','bob',offer(true));assert.equal(a.status,201,JSON.stringify(a.data));assert.equal(b.status,201,JSON.stringify(b.data));return {a:a.data.id,b:b.data.id};}
async function request(call){const {a,b}=await pair(call);const r=await call('requests','alice',{listingId:b,sourceListingId:a});assert.equal(r.status,201,JSON.stringify(r.data));return {a,b,r:r.data.id};}
test('authentication and owner-scoped profile validation',async()=>{const {call}=setup();assert.equal((await call('session',null)).data.user,null);for(const p of ['listings','mine','requests','dashboard','notifications','profile','export'])assert.equal((await call(p,null)).status,401);await accounts(call);assert.equal((await call('profile','alice',{...profile('alice'),userId:'bob'})).status,400);assert.equal((await call('profile','bob')).data.profile.display_name,'bob');assert.equal((await call('admin','alice')).status,403);});
test('CSRF, body size, JSON media type and restrictive headers',async()=>{const {call}=setup();assert.equal((await call('profile','alice',profile('alice'),{origin:'https://evil.test'})).status,403);assert.equal((await call('profile','alice',profile('alice'),{'X-TravelSwap-Request':''})).status,403);assert.equal((await call('profile','alice',profile('alice'),{'Content-Type':'text/plain'})).status,415);assert.equal((await call('profile','alice',{displayName:'x'.repeat(9000)})).status,413);const r=await call('session');assert.equal(r.headers.get('Cache-Control'),'no-store');assert.match(r.headers.get('Content-Security-Policy'),/object-src 'none'/);});
test('listing CRUD, persistence and ownership',async()=>{const {call,DB}=setup();const {a}=await pair(call);assert.equal((await call('listings/'+a+'/edit','eve',offer())).status,404);assert.equal((await call('listings/'+a+'/delete','eve',{})).status,404);assert.equal((await call('listings/'+a+'/edit','alice',{...offer(),amount:'12000'})).status,200);assert.equal((await call('mine')).data.listings[0].amount,1200000);assert.equal((await call('listings/'+a+'/close','alice',{})).status,200);assert.equal((await call('listings/'+a+'/delete','alice',{})).status,200);assert.equal((await call('mine')).data.listings.length,0);assert.ok(DB.sql.prepare('SELECT deleted_at FROM listings WHERE id=?').get(a).deleted_at);});
test('matching is deterministic with exact 40/20/20/20 weights',async()=>{const a={...offer(),amount:1000000,start_date:month()+'-01'},b={...offer(true),amount:380000,start_date:month()+'-01'};assert.deepEqual(matchListings(a,b).components,{currency:40,destination:20,date:20,amount:20});assert.equal(matchListings(a,b).matchScore,100);assert.equal(matchListings(a,{...b,amount:190000}).components.amount,10);assert.equal(matchListings(a,{...b,origin:'Australia'}).components.destination,0);assert.equal(matchListings(a,{...b,have:'AUD'}).compatible,false);const {call}=setup();await pair(call);const found=(await call('listings')).data.listings;assert.equal(found[0].matchScore,100);assert.equal(found[0].owner_id,undefined);assert.equal(found[0].email,undefined);});
test('reject invalid amounts, dates, directions and supplied ownership',async()=>{const {call}=setup();await accounts(call);for(const b of [{...offer(),amount:'-1'},{...offer(),amount:'1e5'},{...offer(),need:'INR'},{...offer(),travelMonth:'2000-01'},{...offer(),travelMonth:'2026-13'},{...offer(),owner_id:'bob'}])assert.equal((await call('listings','alice',b)).status,400);});
test('requests reject duplicates, own listings and unauthorized source',async()=>{const {call}=setup();const {a,b,r}=await request(call);assert.equal((await call('requests','alice',{listingId:a,sourceListingId:a})).status,400);assert.equal((await call('requests','alice',{listingId:b,sourceListingId:a})).status,409);assert.equal((await call('requests','eve',{listingId:b,sourceListingId:a})).status,404);assert.equal((await call('requests/'+r+'/accept','alice',{})).status,403);assert.equal((await call('requests/'+r+'/accept','eve',{})).status,404);assert.equal((await call('listings/'+a+'/edit','alice',offer())).status,409);});
test('complete end-to-end listing, request, conversation, notifications and completion',async()=>{const {call,DB}=setup();const {a,b,r}=await request(call);assert.equal((await call('dashboard','bob')).data.counts.incoming,1);assert.equal((await call('requests/'+r+'/messages','alice',{message:'Too early'})).status,409);assert.equal((await call('requests/'+r+'/accept','bob',{})).status,200);assert.equal((await call('dashboard','alice')).data.counts.conversations,1);assert.equal((await call('requests/'+r+'/messages','alice',{message:'Hello from a fictional trip.'})).status,201);assert.equal((await call('requests/'+r+'/messages','bob',{message:'Hello, I can see your message.'})).status,201);assert.equal((await call('requests/'+r+'/messages','bob')).data.messages.length,2);assert.equal((await call('requests/'+r+'/messages','bob')).data.messages.length,2);assert.equal((await call('requests/'+r+'/messages','eve')).status,404);assert.equal((await call('requests/'+r+'/messages','eve',{message:'intruder'})).status,404);const n=await call('notifications','bob');assert.equal(n.data.unread,2);await call('notifications/read','eve',{id:n.data.notifications[0].id});assert.equal((await call('notifications','bob')).data.unread,2);await call('notifications/read','bob',{});assert.equal((await call('notifications','bob')).data.unread,0);assert.equal((await call('requests/'+r+'/complete','alice',{})).status,200);assert.equal((await call('requests','bob')).data.requests[0].status,'completed');assert.equal((await call('dashboard','alice')).data.counts.completed,1);assert.equal((await call('requests/'+r+'/complete','bob',{})).status,409);assert.equal((await call('requests/'+r+'/messages','alice',{message:'late'})).status,409);assert.equal((await call('requests/'+r+'/messages','alice')).data.messages.length,2);assert.equal(DB.sql.prepare('SELECT status FROM listings WHERE id=?').get(a).status,'closed');assert.ok(DB.sql.prepare('SELECT COUNT(*) AS n FROM audit_events').get().n>5);});
test('only one request can consume a listing',async()=>{const {call}=setup();const {b,r}=await request(call);const c=(await call('listings','eve',offer())).data.id;const second=(await call('requests','eve',{listingId:b,sourceListingId:c})).data.id;const result=await Promise.all([call('requests/'+r+'/accept','bob',{}),call('requests/'+second+'/accept','bob',{})]);assert.equal(result.filter(x=>x.status===200).length,1);assert.equal(result.filter(x=>x.status===409).length,1);});
test('decline, cancel and close prevent invalid transitions',async()=>{const {call}=setup();const {a,r}=await request(call);assert.equal((await call('requests/'+r+'/complete','alice',{})).status,409);await call('listings/'+a+'/close','alice',{});assert.equal((await call('requests/'+r+'/accept','bob',{})).status,409);assert.equal((await call('requests')).data.requests[0].status,'cancelled');});
test('block/report and moderation enforce account boundaries',async()=>{const {call}=setup();const {r}=await request(call);const p=(await call('profile','bob')).data.profile.public_id;await call('requests/'+r+'/accept','bob',{});assert.equal((await call('blocks','alice',{publicId:p})).status,200);assert.equal((await call('requests/'+r+'/messages','bob',{message:'blocked'})).status,403);assert.equal((await call('listings','alice')).data.listings.length,0);assert.equal((await call('reports','alice',{publicId:p,reason:'Testing the report and moderation workflow.'})).status,201);const report=(await call('admin','owner')).data.reports[0];assert.equal((await call('admin','eve',{reportId:report.id,action:'suspend'})).status,403);assert.equal((await call('admin','owner',{reportId:report.id,action:'suspend'})).status,200);assert.equal((await call('profile','bob')).status,403);});
test('transaction failure rolls back acceptance and notifications',async()=>{const {call,DB}=setup();const {r}=await request(call);DB.sql.exec("CREATE TRIGGER fail_listing BEFORE UPDATE ON listings BEGIN SELECT RAISE(ABORT,'secret failure'); END;");const result=await call('requests/'+r+'/accept','bob',{});assert.equal(result.status,503);assert.doesNotMatch(JSON.stringify(result.data),/secret/);assert.equal((await call('requests','alice')).data.requests[0].status,'pending');assert.equal((await call('notifications','alice')).data.unread,0);});
test('export, deletion, redaction and write limits',async()=>{const {call,DB}=setup();const {r}=await request(call);await call('requests/'+r+'/accept','bob',{});await call('requests/'+r+'/messages','alice',{message:'This will be redacted.'});assert.equal((await call('export','alice')).data.messages.length,1);assert.equal((await call('profile/delete','alice',{confirm:'DELETE'})).status,200);assert.equal(DB.sql.prepare('SELECT body FROM messages').get().body,'[Deleted by author]');assert.equal((await call('mine','bob')).data.listings[0].status,'closed');assert.equal((await call('profile','alice',profile('alice'))).status,403);let response;for(let i=0;i<45;i++)response=await call('profile','eve',profile('eve'));assert.equal(response.status,429);});
test('migration preserves prior interest and profile data',()=>{const DB=database();const original=readFileSync('drizzle/0000_travelswap.sql','utf8'),pilot=readFileSync('drizzle/0001_interest_pilot.sql','utf8');const Old=database();Old.sql.close();const {DatabaseSync}=process.getBuiltinModule('node:sqlite'),sql=new DatabaseSync(':memory:');sql.exec(original);sql.exec(pilot);sql.prepare("INSERT INTO profiles VALUES('legacy','public-legacy','Legacy',0,0,1)").run();sql.prepare("INSERT INTO interests VALUES('legacy','INR-TWD','2026-12','pilot-v1',1)").run();sql.exec(readFileSync('drizzle/0002_student_prototype.sql','utf8'));assert.equal(sql.prepare('SELECT display_name FROM profiles').get().display_name,'Legacy');assert.equal(sql.prepare('SELECT COUNT(*) AS n FROM interests').get().n,1);assert.equal(sql.prepare('PRAGMA foreign_key_check').all().length,0);sql.close();DB.sql.close();});

test('concurrent acceptance of the same request creates only one notification',async()=>{const {call}=setup();const {r}=await request(call);const results=await Promise.all([call('requests/'+r+'/accept','bob',{}),call('requests/'+r+'/accept','bob',{})]);assert.equal(results.filter(x=>x.status===200).length,1);assert.equal(results.filter(x=>x.status===409).length,1);assert.equal((await call('notifications','alice')).data.unread,1);});
test('declined requests cannot be accepted later',async()=>{const {call}=setup();const {r}=await request(call);assert.equal((await call('requests/'+r+'/decline','bob',{})).status,200);assert.equal((await call('requests/'+r+'/accept','bob',{})).status,409);assert.equal((await call('requests','alice')).data.requests[0].status,'declined');});
test('local unverified email cannot grant administrator authority',async()=>{const {call,env}=setup();env.LOCAL_AUTH=true;await accounts(call);assert.equal((await call('admin','owner')).status,403);env.ADMIN_USER_ID='owner';assert.equal((await call('admin','owner')).status,200);});
