export class HttpError extends Error { constructor(status,message){super(message);this.status=status;} }
export const fail=(status,message)=>{throw new HttpError(status,message);};
export const currencies=['INR','TWD','AUD'];
export function text(value,min,max,label){if(typeof value!=='string')fail(400,`${label} is required.`);const s=value.trim().normalize('NFC');if(s.length<min||s.length>max||/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/.test(s))fail(400,`${label} must be ${min}–${max} characters.`);return s;}
export function currency(v){if(!currencies.includes(v))fail(400,'Choose a supported currency.');return v;}
export function money(v){if(typeof v!=='string'||!/^\d{1,7}(\.\d{1,2})?$/.test(v))fail(400,'Use an amount with at most two decimal places.');const [whole,fraction='']=v.split('.');const minor=Number(whole)*100+Number(fraction.padEnd(2,'0'));if(minor<100||minor>100000000)fail(400,'Amounts must be between 1 and 1,000,000.');return minor;}
export function date(v){if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(v)||!Number.isFinite(Date.parse(v))||new Date(v).toISOString().slice(0,10)!==v)fail(400,'Choose a valid date.');return v;}
export function id(v){if(typeof v!=='string'||!/^[a-zA-Z0-9_-]{1,64}$/.test(v))fail(400,'Invalid record.');return v;}
export function mutationGuard(request){if(request.headers.get('sec-fetch-site')==='cross-site')fail(403,'Cross-site requests are not allowed.');const origin=request.headers.get('origin');if(!origin||origin!==new URL(request.url).origin)fail(403,'Please submit from TravelSwap.');if(request.headers.get('x-travelswap-request')!=='1')fail(403,'Refresh the page and try again.');if(request.headers.get('content-type')?.split(';')[0].trim()!=='application/json')fail(415,'Use a JSON request.');}
export async function body(request){const reader=request.body?.getReader();if(!reader)fail(400,'Request body is required.');let size=0;const chunks=[];while(true){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>8192){await reader.cancel();fail(413,'This request is too large.');}chunks.push(value);}const all=new Uint8Array(size);let offset=0;for(const chunk of chunks){all.set(chunk,offset);offset+=chunk.length;}try{const result=JSON.parse(new TextDecoder().decode(all));if(!result||typeof result!=='object'||Array.isArray(result))throw Error();return result;}catch{fail(400,'Invalid JSON request.');}}
export function publicHeaders(type='application/json; charset=utf-8'){return {'Content-Type':type,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'strict-origin-when-cross-origin','Permissions-Policy':'camera=(), microphone=(), geolocation=(), payment=()','Content-Security-Policy':"default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'self'; font-src 'self'; base-uri 'none'; object-src 'none'; form-action 'self'; frame-ancestors 'self' https://chatgpt.com https://*.chatgpt.com",'Strict-Transport-Security':'max-age=31536000; includeSubDomains'};}
